baseurl = "https://adsoncostanzifilho.github.io/"
title = "Adson Costanzi Filho"
theme = "hugo-universal-theme"
languageCode = "en-us"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"
# Enable comments by entering your Disqus shortname
# disqusShortname = "devcows"

publishDir = "public"

#highlightjsTheme = "github"

# Enable emoji inside RMarkdown
enableEmoji = true

# Enable Google Analytics by entering your tracking code
googleAnalytics = "G-HFMXRQE7HX"
# Define the number of posts per page
paginate = 5

[menu]

# Main menu

[[menu.main]]
    identifier="home"
    name = "Home"
    url  = "/"
    weight = 1


[[menu.main]]
    identifier = "about"
    name = "About"
    url  = "/about/"
    weight = 2


[[menu.main]]
    identifier="blog"
    name = "Blog"
    url  = "/blog/"
    weight = 3

# Top bar social links menu

[params]
    viewMorePostLink = "/blog/"
    author = "DevCows"
    defaultKeywords = ["devows", "hugo", "go"]
    mainSections = ["blog"]
    defaultDescription = "Site template made by devcows using hugo"

    # Social media
    facebook_site = "" # the Facebook handle of your site ('https://www.facebook.com/HANDLE')
    twitter_site = "GoHugoIO" # the Twitter handle of your site (without the '@')
    default_sharing_image = "img/sharing-default.png"

    # Google Maps widget: If `googleMapsApiKey` is not set, no key will be passed to Google (which likely results in a broken map widget).
    enableGoogleMaps = false
    googleMapsApiKey = "AIzaSyCFhtWLJcE30xOAjcbSFi-0fnoVmQZPb1Y"

    latitude = "-12.043333"
    longitude = "-77.028333"

    #Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "violet"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 50 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - register your account to https://formspree.io/register
    # - login and create new form
    # - set your form's endpoint url under 'formspree_action' below
    # - upload the generated site to your server
    # - test a dummy email yourself
    # - you're done. Happy mailing!
    #
    #Enable the contact form by entering your Formspree.io endpoint url
    formspree_action = "https://formspree.io/sample/of/endpoint"
    contact_form_ajax = false

    about_us = "<p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.</p>"
    copyright = "Copyright (c) 2015 - 2016, YourCompany; all rights reserved."

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    logo = "img/logo.png"
    logo_small = "img/logo-small.png"
    address = """<p class="text-uppercase"><strong>Universal Ltd.</strong>
        <br>13/25 New Avenue
        <br>Newtown upon River
        <br>45Y 73J
        <br>England
        <br>
        <strong>Great Britain</strong>
      </p>
      """

[Permalinks]
    blog = "/blog/:year/:month/:day/:slug/"

# Enable or disable top bar with social icons
[params.topbar]
    enable = false
    text = """<p class="hidden-sm hidden-xs">Contact us on +420 777 555 333 or hello@universal.com.</p>
      <p class="hidden-md hidden-lg"><a href="#" data-animate-hover="pulse"><i class="fas fa-phone"></i></a>
      <a href="#" data-animate-hover="pulse"><i class="fas fa-envelope"></i></a>
      </p>
      """

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true


[params.see_more]
    enable = true
    title = "Statistician/Data Scientist"
    subtitle = "Hi! Nice to meet you, my name is Adson."
    link_url = "/files/cv.pdf"
    link_text = "Resumé"

[params.clients]
    enable = true
    title = "OTHER BLOGS"
    subtitle = "These are some of my friends` pages (which I used as an inspiration for the development of this one). I strongly recommend taking a look at it all..."

[params.recent_posts]
    enable = true
    title = "BLOG"
    subtitle = "I created this page as a repository of some of my ideas and projects related to statistics, data science, and of course, R. I hope you find something interesting here.."

    # syntax highlight
    #highlightjsVersion = "9.12.0"
    #highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    #highlightjsLang = ["r", "yaml"]
    #highlightjsTheme = "tango"


